engine:
  name: tofu

hooks:
  all:
    pre:
      - type: run
        cmd: ['echo', '::add-mask::FOOBAR']
        visible_on: always
      - type: run
        cmd: ['echo', 'BOOMBAZ', 'FOOBAR']
        visible_on: always
